Repository raphaelsty/neural-cherche, pull requests merged in 2024-04, with the labels that each got.

#18 Update sparse_embed.py
  neural_cherche/retrieve/__init__.py
  neural_cherche/retrieve/bm25.py
  neural_cherche/retrieve/sparse_embed.py
Labels: enhancement

#20 Run formatting with black and Isort imports. Raise warnings if duplicates queries.
  neural_cherche/rank/colbert.py
  neural_cherche/retrieve/__init__.py
  neural_cherche/retrieve/bm25.py
  neural_cherche/retrieve/sparse_embed.py
  neural_cherche/retrieve/splade.py
  neural_cherche/retrieve/tfidf.py
  neural_cherche/utils/__init__.py
  neural_cherche/utils/warnings.py
Labels: documentation

#22 update bm25
  neural_cherche/retrieve/bm25.py
Labels: bug

#24 accelerate bm25
  neural_cherche/retrieve/bm25.py
Labels: enhancement

#25 update bm25
  neural_cherche/retrieve/bm25.py
  neural_cherche/retrieve/tfidf.py
Labels: enhancement
